In [1]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
# A tensor in deep learning is simply an N-dimensional array
# We start this tutorial by some simple manipulations of tensors

In [3]:
# Create an uninitialized tensor
x = torch.empty(4, 2)
print(x)

tensor([[-8.0649e+08,  3.0673e-41],
        [ 5.6052e-45,  0.0000e+00],
        [        nan,  1.6255e-43],
        [ 1.1578e+27,  4.1666e+34]])


In [4]:
# Create a tensor initialized with ones and zeros
x = torch.zeros(4, 2, dtype=torch.double) # We can specify the type of the elements
print(x)
x = torch.ones(4, 2, dtype=torch.double)
print(x)
# Create an randomly initialized tensor
y = torch.rand(4, 2, dtype=torch.double)
print(y)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[0.2121, 0.0374],
        [0.6777, 0.6308],
        [0.6824, 0.0540],
        [0.5312, 0.7292]], dtype=torch.float64)


In [5]:
# Check the size of a tensor
print(x.size())

torch.Size([4, 2])


In [6]:
# One can also create tensors directly from data
print(torch.tensor([3.33, 2.64]))

tensor([3.3300, 2.6400])


In [7]:
# Operations of tensors are very similar to those of NumPy
print(x + y)
output = torch.empty(4, 2, dtype=torch.double)
print(torch.add(x, y, out=output)) # Output argument can be added as well
print(y.add_(x)) # In-place operations should be followed by _
print(y) # We can see that y is mutated

tensor([[1.2121, 1.0374],
        [1.6777, 1.6308],
        [1.6824, 1.0540],
        [1.5312, 1.7292]], dtype=torch.float64)
tensor([[1.2121, 1.0374],
        [1.6777, 1.6308],
        [1.6824, 1.0540],
        [1.5312, 1.7292]], dtype=torch.float64)
tensor([[1.2121, 1.0374],
        [1.6777, 1.6308],
        [1.6824, 1.0540],
        [1.5312, 1.7292]], dtype=torch.float64)
tensor([[1.2121, 1.0374],
        [1.6777, 1.6308],
        [1.6824, 1.0540],
        [1.5312, 1.7292]], dtype=torch.float64)


In [8]:
# Resize tensors
z = x.view(8)
print(z.size())
print(z)
z = x.view(-1, 4) # -1 means inferring the dimension from other dimensions
print(z.size())
print(z)

torch.Size([8])
tensor([1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)
torch.Size([2, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [9]:
# One can convert a tensor into an NumPy array or vice-versa,
# notice that they will share the same underlying memory location
y = x.numpy()
print(y)
x.add_(1)
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [10]:
x = np.ones(5)
y = torch.from_numpy(x)
print(y)
np.add(x, 1, out=x)
print(y)


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [11]:
# Now let's manipulate tensors on GPU
x = torch.rand(7, 7)
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device) # We can either create directly a tensor on GPU
    x = x.to(device) # Or, push a CPU tensor "to" your GPU device
    z = x + y
    print(z)
    print(z.to("cpu"))


/home/xuedong/Programming/Trochilus/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py:116: UserWarning: 
    Found GPU0 Quadro K1100M which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))


RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /pytorch/aten/src/THC/generic/THCTensorMath.cu:15